baseurl = ""
DefaultContentLanguage = "pt-br"
title = "rafaelbecker.dev"
theme = "PaperMod"
metaDataFormat = "yaml"
enableEmoji = true
enableGitInfo = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
summaryLength = 20

[menus]
#[[menus.main]]
#    name = 'Search'
#    url = 'search/'
#    weight = 10
[[menus.main]]
    weight = 10
    name = 'About'
    url = 'page/about/'

[Params]
    mainSections = ["post","posts"]
    dateFormat = "January 2, 2006"
    comments = true
    readingTime = true
    wordCount = true
    useHLJS = true
    delayDisqus = true
    showRelatedPosts = true
    showShareButtons = true
    ShareButtons = ["linkedin", "twitter"]
    minifyOutput = false

[Author]
    name = "Rafael Becker"
    email = "realfabecker@outlook.com"
    github = "realfabecker"
    twitter = "rafaelbeecker"
    linkedin = "rafaelbeecker"