name: deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy: 
    name: deploy
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.124.1'

      - name: Build hugo
        run: hugo
          
      - name: Upload S3
        run: |
          aws s3 sync public s3://rafaelbecker.dev --exclude 'public/media/*' --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Cloudfront Create Invalidation
        env: 
          DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws cloudfront create-invalidation \
              --distribution-id $DISTRIBUTION_ID \
              --invalidation-batch '{"Paths": {"Quantity":1, "Items":["/*"]}, "CallerReference": "cd"}'
