name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy: 
    name: deploy
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.124.1'

      - name: Build hugo
        run: hugo
          
      - name: Upload S3
        run: aws s3 sync public s3://rafaelbecker.dev --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}